#!/usr/bin/perl

use lib 'lib';
use Play::Test;

use Email::Sender::Simple;
use Play::Flux;

use Log::Any qw($log);

my $pumper = pumper('sendmail');

$pumper->run;
$log->empty_ok;

use Play::DB qw(db);

# prepare the user
{
    db->users->add({ login => 'test3' });
    db->users->set_settings('test3', { notify_likes => 1, email => 'test3+setting@example.com' });

    # we're not interested in user emails, we're testing genertic email functionality, but we need the user to check notify_field feature
    $pumper->run; $log->clear;
    Email::Sender::Simple->default_transport->clear_deliveries;
}

my $storage = Play::Flux->email;

# legacy item format
$storage->write(['test@example.com', 'test title', 'test body 1']);

# modern format
$storage->write({
    address => 'test2@example.com',
    subject => 'test title 2',
    body => 'test body 2',
});

$storage->write({
    address => 'test3@example.com',
    subject => 'test title 3',
    body => 'test body 3',
    notify_field => 'notify_likes',
    login => 'test3',
});

$storage->commit;

$pumper->run;
$log->contains_ok(qr/3 emails sent/);
$log->clear;

my @deliveries = Email::Sender::Simple->default_transport->deliveries;
is scalar @deliveries, 3, 'expected 3 emails';

is $deliveries[0]->{email}->get_body, "test body 1\r\n";
is $deliveries[1]->{email}->get_body, "test body 2\r\n";
like $deliveries[2]->{email}->get_body, qr/test body 3/;
like $deliveries[2]->{email}->get_body, qr/Unsubscribe/, 'unsubscribe link generated by notify_field';
Email::Sender::Simple->default_transport->clear_deliveries;

done_testing;
